### ISSUE TITLE
Compare d3.js, chart.js and p5.js and choose

### ISSUE THREAD

**Issue by cathyatseneca** [Seneca-CDOT/dashboard2016#13]
choose one of the 3 libraries to perform the drawing aspect of this project.  Keep in mind that other charts may be added in the future

**Comment by hscasn** [comment]
d3.js and chart.js seem to be perfect for creating charts. however, their APIs are complex. p5.js may not be the best tool for creating these graphs, but it will fit the requirements and will support expansion
